### ISSUE TITLE
[FEATURE] Improve cache feature on iOS

### ISSUE THREAD

**Issue by delfme** [AnonymHK/betterplayer#1]
First of all, my compliments for this initiative! 🎉👏

Cache feature on iOS is built on top of CachingPlayerItem, which is sort of a discoutinued repo
https://github.com/neekeetab/CachingPlayerItem

Given the mood of this repo is to reignite betterplayer and become the goto reference for it, it would make sense to integrate CachingPlayerItem as source file and update/mantain it as well. At the end, it is just a single class with MIT license.

Note: it would be much appreciated if international english will be used as the language for the repository. The majority of the community is not familiar with chinese.

**Comment by AnonymHK** [comment]
Okay, English will be the preferred choice for the repository! This component is being used in our company's project. Due to my busy work, bug fixes and plugin updates will take priority over feature additions. If you can submit a Pull, I will be very happy!

**Comment by delfme** [comment]
Hi, I was out travelling. Will report any bugs. Thx
