### ISSUE TITLE
[BUG] does not exist on pub.dev

### ISSUE THREAD

**Issue by guyluz11** [AnonymHK/betterplayer#19]
This fork is a well maintained source for betterplayer.
@AnonymHK  please upload it to [pub.dev](https://pub.dev/) so that people can use it in their program in a controlled manner (versions and easy and fast install)

**Comment by AnonymHK** [comment]
ok

**Comment by guyluz11** [comment]
Please keep this issue open until you do so.

And when you are done please paste a link here
