### ISSUE TITLE
[BUG] Readme pub.dev link is incorrect

### ISSUE THREAD

**Issue by guyluz11** [AnonymHK/betterplayer#20]
Link in the readme to pub.dev rowting to the original package page.

![image](https://github.com/AnonymHK/betterplayer/assets/9304740/7cbd64cd-f408-4f84-8cf9-9c08c2334e63)

Also make sure that the link in pub.dev links back to this repo
 
 
![image](https://github.com/AnonymHK/betterplayer/assets/9304740/0bd09f85-06a0-4fb2-823c-f323d01595b3)

**Comment by AnonymHK** [comment]
ok!
