### ISSUE TITLE
[BUG] M3U8播放不了，必须指定videoFormat: BetterPlayerVideoFormat.hls,

### ISSUE THREAD

**Issue by wll19890224** [AnonymHK/betterplayer#3]
demo 中 hls_subtitles_page.dart

 BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        Constants.hlsPlaylistUrl,
        useAsmsSubtitles: true);

需要改成
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        Constants.hlsPlaylistUrl,
        videoFormat: BetterPlayerVideoFormat.hls,
        useAsmsSubtitles: true);

怎么没有内部判断url是不是hls？

**Comment by AnonymHK** [comment]
已修正,原库中hls需要自己指定videoFormat，每个人需求场景不同，我改天抽时间处理下自动判断！
